# Generated by Django 4.2.3 on 2023-07-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=15)),
                ('date', models.DateField()),
            ],
        ),
    ]
