# Generated by Django 4.2.3 on 2023-07-29 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contect',
            old_name='Password',
            new_name='Phonenumber',
        ),
    ]
