# Generated by Django 4.2.3 on 2023-07-30 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_rename_password_contect_phonenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contect',
            old_name='Username',
            new_name='name',
        ),
    ]
