# Generated by Django 4.2.3 on 2023-07-30 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_rename_username_contect_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contect',
            old_name='Email',
            new_name='email',
        ),
    ]
